language: node_js
node_js:
  - '12'
branches:
  only:
    - master
deploy:
  provider: heroku
  skip_cleanup: true
  on:
    branch: master
  api_key:
    secure: NdK/z7KygLp8fN/2/ijJ/e0eoivIyFlAfBG02MNZtV7L9eVbr2TuKKsiGUdEnecEywA3VEfg80bg5GRp2L2yOpr+IfyC8DMYwZZ4zul5xrdYSnXjdjHdZfSSY2L6MPf+5D/RkWRlrDyP6p0OsSDYZ5ITCPFtQP9w4vj4qBG3idk224m+APvQ84aAlRM9WIc7gAZsLAadYqTXSOBO3ZqYnWnZaUr4h00ayI3l9uLXegI5NF6NaZicU0SCh2amKrByHU79bWzVsCQJ3fj8yqwwWtCuf+eDQGixTHePGyia/DTVIX2TNO7qKHwYwakm+N4uIDTdzcjx3rUMSYSnXKGi+gAPthgDduceqBKNbHwkc06nN8mEcbjIRMKXe0nBl/ZoCQUXJIGKCorGlhKw8FStW14ibOiUAxxHiT06KbCPjF7yIEcJrUdKXIozlu3iLfd9cp6w5qgVxJ7bhiGZO7/Z6NSNiShv8VemtvDXnm/RgC792ZKggkst9/IdTRQas2dijByu2P6MZ53Jiys3USnaVjqwcNKO0BtB13hf7HzevYnQMBGRBbMAscHj2HR3AuH/8Atl1enGmsFrIfT2o6lpSJeEhCFfGTEnYhliHqhP+m5gZjUKfA2qYnYqJorkxcjjeGJNX2pyMc+UpkVrEGNH7sAfXpEMuKmaSfq1rgtfW0I=
  app: banking-nest-upc-heroku-lab1
notifications:
  email:
    on_failure: change
    on_success: change
